// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSN6jvonilSXzhioQccbWx0or7N4S9-g',
    appId: '1:707439420696:web:c42a70e4d48a3111722a6d',
    messagingSenderId: '707439420696',
    projectId: 'things-stufs',
    authDomain: 'things-stufs.firebaseapp.com',
    storageBucket: 'things-stufs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdkPy-TN5qvla1b_Ma_ihibxXybd1ddiw',
    appId: '1:707439420696:android:7f2f10769720107c722a6d',
    messagingSenderId: '707439420696',
    projectId: 'things-stufs',
    storageBucket: 'things-stufs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCArCd37OuyOE5IGdAc_owPR8bHfT8175w',
    appId: '1:707439420696:ios:9b0129f29c8fff14722a6d',
    messagingSenderId: '707439420696',
    projectId: 'things-stufs',
    storageBucket: 'things-stufs.appspot.com',
    iosClientId: '707439420696-gb6ir9nd70afqmfc3c523ep916b70087.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingStuffs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCArCd37OuyOE5IGdAc_owPR8bHfT8175w',
    appId: '1:707439420696:ios:672b3dddf7cbc810722a6d',
    messagingSenderId: '707439420696',
    projectId: 'things-stufs',
    storageBucket: 'things-stufs.appspot.com',
    iosClientId: '707439420696-nm91e23tnmrv11jfbq2022guq05gqn2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingStuffs.RunnerTests',
  );
}
